# Generated by Django 2.2.1 on 2019-05-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190507_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of service.', max_digits=6, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of specialist.', upload_to='profile_image', verbose_name='image'),
        ),
    ]
