# Generated by Django 2.2.1 on 2019-05-07 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190508_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='seance',
            options={'verbose_name': 'сеанс', 'verbose_name_plural': 'сеансы'},
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={'verbose_name': 'специалист', 'verbose_name_plural': 'специалисты'},
        ),
        migrations.AlterField(
            model_name='order',
            name='seance',
            field=models.ForeignKey(help_text='Дата время и специалист', on_delete=django.db.models.deletion.CASCADE, to='main.Seance', verbose_name='Сеанс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(help_text='Заказанная услуга', on_delete=django.db.models.deletion.CASCADE, to='main.Service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь, оформивший заказ', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='date',
            field=models.DateField(help_text='Дата сеанса.', verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='reserved',
            field=models.BooleanField(default=False, help_text='Занят ли сеанс?', verbose_name='Зарезервирован'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='specialist',
            field=models.ForeignKey(help_text='Специалист.', on_delete=django.db.models.deletion.CASCADE, to='main.Specialist', verbose_name='специалист'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='time',
            field=models.TimeField(help_text='Время сеанса.', verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='image',
            field=models.ImageField(blank=True, help_text='Аватар специлиста.', upload_to='profile_image', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(help_text='Имя специалиста.', max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='position',
            field=models.CharField(help_text='Должность специалиста.', max_length=25, verbose_name='Должность'),
        ),
    ]
