# Generated by Django 2.2.1 on 2019-05-07 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190508_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(help_text='Категория услуги.', on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='категория'),
        ),
    ]
