# Generated by Django 2.2.1 on 2019-05-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
