# Generated by Django 2.2.1 on 2019-05-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
